
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED"

export const ADMIN_LOGOUT = "ADMIN_LOGOUT"



